version: '3'

services:
   pdfoptimize:
    build:
    image: hunsakerconsulting/pdfoptimize
    container_name: pdfoptimize
    environment:
    ports:
    links:
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   pdfconversion:
    build:
    image: hunsakerconsulting/pdfconversion
    container_name: pdfconversion
    environment:
    ports:
    links:
      - pdfoptimize
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   pdfcompression:
    build:
    image: hunsakerconsulting/pdfcompression
    container_name: pdfcompress
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   imageextraction:
    build:
    image: hunsakerconsulting/imageextraction
    container_name: imageextraction
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   imageoptimization:
    build:
    image: hunsakerconsulting/imageoptimization
    container_name: imageoptimization
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   textocrd:
    build:
    image: ocrd/all:maximum-git
    container_name: textocr
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   hocrformatting:
    build:
    image: hunsakerconsulting/hocr
    container_name: hocrformatting
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   uebiterary:
    build:
    image: hunsakerconsulting/<NAME>
    container_name: uebliterarytranscription
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   mathocr:
    build:
    image: hunsakerconsulting/mathocr
    container_name: mathocr
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   uebtechnical:
    build:
    image: hunsakerconsulting/uebtechnicaltranscription
    container_name: uebtechnicaltranscription
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   pretext:
    build:
    image: hunsakerconsulting/pretext
    container_name: pretext
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   daisypipeline2:
    build:
    image: daisyorg/pipeline-assembly
    environment:
      PIPELINE2_WS_HOST: "0.0.0.0"
      PIPELINE2_WS_AUTHENTICATION: "false"
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
       - "pipeline-data:/opt/daisy-pipeline2/data"
       - c:/users/ryan/WORKDIR:/data
   webui:
    build:
    image: daisyorg/pipeline-webui
    environment:
     DAISY_PIPELINE2_URL: http://pipeline:8181/ws
    ports:
     - "9000:9000"
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
    volumes:
     - "webui-data:/opt/daisy-pipeline2-webui/data"
    depends_on:
     daisypipeline2:
      condition: service_healthy
   qualitycontrolepub:
    build:
    image: hunsakerconsulting/qualitycontrolepub
    container_name: qualitycontrolepub
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   tactilegraphics:
    build:
    image: hunsakerconsulting/tactilegraphics
    container_name: tactilegraphics
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   musicocr:
    build:
    image: hunsakerconsulting/musicocr
    container_name: musicocr
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicformatting
      - qualitycontrolmusic
      - webui 
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   musicformatting:
    build:
    image: hunsakerconsulting/musicformatting
    container_name: musicformatting
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   qualitycontrolmusic:
    build:
    image: hunsakerconsulting/qualitycontrolmusic
    container_name: qualitycontrolmusic
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - musicbraille
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
   musicbraille:
    build:
    image: hunsakerconsulting/musicbraille
    container_name: musicbraille
    environment:
    ports:
    links:
      - pdfoptimize
      - pdfconversion
      - pdfcompression
      - imageextraction
      - imageoptimization
      - textocrd
      - hocrformatting
      - uebliterary
      - uebtechnical
      - mathocr
      - pretext
      - daisypipeline2
      - qualitycontrolepub
      - tactilegraphics
      - musicocr
      - musicformatting
      - qualitycontrolmusic
      - webui
    volumes:
      - c:/users/ryan/WORKDIR:/data
    environment:
volumes:
  - c:/users/ryan/WORKDIR:/data
  - pipeline-data:
  - webui-data: