version: "3.9"

services:
  preprocessing:
    stdin_open: "true"
    tty: "true"
    build:
      context: ./imagepreprocessing
      dockerfile: Dockerfile
    image: hunsakerconsulting/imageprocessingpipeline
    container_name: preprocessing
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  ocrdpipeline:
    build:
      context: ./ocrd-all-maximum-git
      dockerfile: Dockerfile
    image: hunsakerconsulting/ocrd-all-maximum-git:latest
    container_name: ocrdpipeline
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  easyocrpipeline:
    build:
      context: ./easyocrpipeline
      dockerfile: Dockerfile
    image: hunsakerconsulting/easyocrpipeline:latest
    container_name: easyocrpipeline
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  ocr4allpipeline:
    build:
      context: ./ocr4allpipeline
      dockerfile: Dockerfile
    image: hunsakerconsulting/ocr4allpipeline
    container_name: ocr4allpipeline
    ports:
      - "8080:8080"
    volumes:
      - OCR_DATA_DIR:/var/ocr4all/data
      - OCR_MODEL_DIR:/var/ocr4all/models/custom
  ocularpipeline:
    build:
      context: ./ocular
      dockerfile: Dockerfile
    image: hunsakerconsulting/ocularocrpipeline:latest
    container_name: ocularocrpipeline
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  daisypipeline2:
    build:
      context: ./daisypipeline2
      dockerfile: Dockerfile
    image: hunsakerconsulting/daisypipeline2:latest
    container_name: daisypipeline2
    environment:
      PIPELINE2_WS_HOST: "0.0.0.0"
      PIPELINE2_WS_AUTHENTICATION: "false"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 40s
    volumes:
      - pipeline-data:/opt/daisy-pipeline2/data
  webui:
    image: daisyorg/pipeline-webui:latest
    environment:
      DAISY_PIPELINE2_URL: http://pipeline:8181/ws
    ports:
      - "9000:9000"
    volumes:
      - webui-data:/opt/daisy-pipeline2-webui/data
    depends_on:
      daisypipeline2:
        condition: service_started
  audiverisomr:
    build:
      context: ./audiverisomr
      dockerfile: Dockerfile
    image: hunsakerconsulting/audiverisomr
    container_name: audiverisomr
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  Mozart:
    build:
      context: ./Mozart
      dockerfile: Dockerfile
    image: hunsakerconsulting/mozartomr
    container_name: mozartomr
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  Moonlight:
    build:
      context: ./moonlight
      dockerfile: Dockerfile
    image: hunsakerconsulting/moonlightomr
    container_name: moonlightomr
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
  musicomrpipelines:
    build:
      context: ./musicpipeline
      dockerfile: Dockerfile
    image: hunsakerconsulting/musicpreprocessingpipeline
    container_name: musicpreprocessing
    volumes:
      - type: bind
        source: ~/WORKDIR
        target: /data
volumes:
  pipeline-data:
  webui-data:
  OCR_DATA_DIR:
  OCR_MODEL_DIR:
##########
# EOF
##########
